### ISSUE TITLE
Cuda allocation failed- Version 0.17.1 Windows standalone

### ISSUE THREAD

**Issue by 01Bookworm01** [octimot/StoryToolkitAI#23]
I've tried to transcribe a timeline a few times now. Every time it goes to do so, it gives me this error back:

`INFO: Starting to transcribe Timeline 1`
`INFO: Using cuda for Torch / Whisper.`
`INFO: Transcribing Timeline 1.`
`This may take a while.`
`librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)`
`ERROR: Traceback (most recent call last):`
`  File "app.py", line 4659, in transcribe_from_queue`
`  File "app.py", line 5011, in whisper_transcribe`
`  File "app.py", line 4755, in whisper_transcribe_segments`
`  File "whisper\transcribe.py", line 181, in transcribe
    result: DecodingResult = decode_with_fallback(segment)`
`  File "whisper\transcribe.py", line 117, in decode_with_fallback
    decode_result = model.decode(segment, options)`
 ` File "torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)`
`  File "whisper\decoding.py", line 701, in decode
    result = DecodingTask(model, options).run(mel)`
`  File "torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)`
 ` File "whisper\decoding.py", line 617, in run
    audio_features: Tensor = self._get_audio_features(mel)  # encoder forward pass`
`  File "whisper\decoding.py", line 561, in _get_audio_features
    audio_features = self.model.encoder(mel)`
`  File "torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)`
`  File "whisper\model.py", line 156, in forward
    x = block(x)`
`  File "torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)`
`  File "whisper\model.py", line 124, in forward
    x = x + self.attn(self.attn_ln(x), mask=mask, kv_cache=kv_cache)`
 ` File "torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)`
`  File "whisper\model.py", line 73, in forward
    q = self.query(x)`
`File "torch\nn\modules\module.py", line 1130, in _call_impl
 return forward_call(*input, **kwargs)`
`  File "whisper\model.py", line 36, in forward
    return F.linear( `
`RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling ``cublasCreate(handle)`` `

For the last line, it's just one ` on either side of cublas. Formatting was a bit weird there.

From what I can tell, this is all on whispers side correct? It's failing to allocate the cuda correctly, even though I am using only the medium model? Would it be advised for me to try it with only Davinci and storykit open to eliminate other applications drawing resources away as a factor?

**Comment by octimot** [comment]
I haven't peaked inside the code which deals with the CUDA resources allocation, but I think your intuition is correct.

I would not use any other software when the tool is transcribing to prevent this from happening. As a matter of fact, even playing back something GPU intense in Resolve while transcribing could be problematic, since both applications need a lot of GPU to work.

What are you GPU specs BTW?

**Comment by 01Bookworm01** [comment]
I'm running with a Nvidia geforce rtx 3070, which has 8 gigs of ram built into it. So it's no lightweight by any means

Side note as well, I ran the toolkit version I had from before, the one inside the virtual environment, and it worked like a dream. Everything I had open was still open, so I think we can rule resource hungry applications out for this instance. I will keep it in mind though.

**Comment by octimot** [comment]
Which version was the one that worked better?

**Comment by 01Bookworm01** [comment]
It was the 0.16.16 one. Like I said before, the 0.17.1 one wasn't transcribing after getting the audio file. I'm trying it again now though to see if it plays any better now that everything else is closed.

**Comment by 01Bookworm01** [comment]
And 0.17.1 is working now. I guess it's just more greedy than the older version, which ran when everything else was still open. So I guess this can be marked as close now. Just make sure that the program is the only thing running if you get cuda errors.
