### ISSUE TITLE
CUDA not available in CUDA machines

### ISSUE THREAD

**Issue by iuin1034** [octimot/StoryToolkitAI#70]
good afternoon,
I am using a gtx 3060 graphics card, but cuda does not appear in the settings, can you tell me for what reason?
![image](https://user-images.githubusercontent.com/107824115/226169598-b41e7ed3-08af-414f-b2d9-eacb0d366e36.png)
![image](https://user-images.githubusercontent.com/107824115/226169632-20e91ede-2480-47d2-9bf7-466a323b52d1.png)
I used the instructions in step 7

**Comment by octimot** [comment]
Can you try to redo step 7 inside the venv and post what you get in the command line?

Also, please add the app.log when reporting, because it's hard to understand what is happening otherwise.

**Comment by iuin1034** [comment]
comand line
![image](https://user-images.githubusercontent.com/107824115/226599485-4177b92f-6a4d-46a1-b51d-027574b6ba29.png)
[app.log](https://github.com/octimot/StoryToolkitAI/files/11027979/app.log)

**Comment by barzoock** [comment]
@iuin1034 same problem. have you found a solution?

**Comment by octimot** [comment]
Did you follow step 9 notes regarding CUDA?
```
pip uninstall torch
pip cache purge
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
```

Cheers!

**Comment by barzoock** [comment]
> Did you follow [step 9](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#9-install-all-the-stuff-the-tool-requires) notes regarding CUDA?
> 
> ```
> pip uninstall torch
> pip cache purge
> pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
> ```
> 
> Cheers!

Yes done the steps but still (auto/cpu) only.
I have RTX 4090

**Comment by iuin1034** [comment]
Alas, none of the above helps, tried reinstalling python 3.9, did not help

**Comment by octimot** [comment]
I managed to reproduce the issue on one of our machines and the following solved it.

@barzoock @iuin1034 Please try the following in your virtual environment and let me know if it worked:

```
pip uninstall torch torchaudio torchvision
pip cache purge
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
```

We are forcing a cuda 11.7 compatible install instead of the 11.6 proposed in the installation instructions.

**Comment by barzoock** [comment]
> I managed to reproduce the issue on one of our machines and the following solved it.
> 
> @barzoock @iuin1034 Please try the following in your virtual environment and let me know if it worked:
> 
> ```
> pip uninstall torch torchaudio torchvision
> pip cache purge
> pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
> ```
> 
> We are forcing a cuda 11.7 compatible install instead of the 11.6 proposed in the installation instructions.

Confirm it works. Thank you ♥

**Comment by octimot** [comment]
Cool, thanks for the feedback!

@iuin1034 I'll close the issue for now, but feel free to re-open if this solution didn't work for you.
